services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: simuser
      POSTGRES_PASSWORD: simpass
      POSTGRES_DB: simdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./src/Handelssim.Api
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=simdb;Username=simuser;Password=simpass
    ports:
      - "8080:80"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
